px1: 2.5
py1: 7
pz1: 0
ox1: 0 
oy1: 0
oz1: 1.5
ow1: 1

px2: 0.5
py2: 7
pz2: 0  
ox2: 0  
oy2: 0  
oz2: 1.5
ow2: 1

px3: 0.5
py3: 6.5
pz3: 0  
ox3: 0  
oy3: 0
oz3: -7.5
ow3: 1

px4: 0.5
py4: 4
pz4: 0  
ox4: 0  
oy4: 0  
oz4: -7.5
ow4: 1

px5: 1.9
py5: 3.2
pz5: 0  
ox5: 0  
oy5: 0  
oz5: -2
ow5: 1

px6: 2.9
py6: 3.2
pz6: 0  
ox6: 0  
oy6: 0  
oz6: -1
ow6: 1

opx: 5.5
opy: 0  
opz: 0  
oox: 0  
ooy: 0  
ooz: 0  
oow: 1

hpx: 0
hpy: 0  
hpz: 0  
hox: 0  
hoy: 0  
hoz: 0  
how: 1

TURNING_SPEED: 1.4
TURNING_TIME: 3.0